[[
  {
    "name": "flask.request",
    "service": "flask",
    "resource": "GET /helloworld",
    "trace_id": 0,
    "span_id": 1,
    "parent_id": 0,
    "type": "web",
    "error": 1,
    "meta": {
      "_dd.p.dm": "-0",
      "flask.endpoint": "error",
      "flask.url_rule": "/helloworld",
      "flask.version": "0.12.5",
      "http.method": "GET",
      "http.status_code": "500",
      "http.url": "http://localhost/helloworld",
      "runtime-id": "cf4bed8941774ec2bdeae7c0e14f50e5"
    },
    "metrics": {
      "_dd.agent_psr": 1.0,
      "_dd.measured": 1,
      "_dd.top_level": 1,
      "_dd.tracer_kr": 1.0,
      "_sampling_priority_v1": 1,
      "system.pid": 48780
    },
    "duration": 7032000,
    "start": 1657055774809491000
  },
     {
       "name": "flask.try_trigger_before_first_request_functions",
       "service": "flask",
       "resource": "flask.try_trigger_before_first_request_functions",
       "trace_id": 0,
       "span_id": 2,
       "parent_id": 1,
       "error": 1,
       "meta": {
         "error.msg": "",
         "error.stack": "Traceback (most recent call last):\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/contrib/flask/helpers.py\", line 36, in wrapper\n    return wrapped(*args, **kwargs)\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/.riot/venv_py3615_flask~0120_pytest~30_more_itertools8110_itsdangerous20_markupsafe20/lib/python3.6/site-packages/flask/app.py\", line 1654, in try_trigger_before_first_request_functions\n    func()\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/contrib/flask/wrappers.py\", line 25, in trace_func\n    return wrapped(*args, **kwargs)\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/tests/contrib/flask/test_request.py\", line 343, in error\n    raise Exception()\nException\n",
         "error.type": "builtins.Exception"
       },
       "duration": 4555000,
       "start": 1657055774809924000
     },
        {
          "name": "tests.contrib.flask.test_request.error",
          "service": "flask",
          "resource": "tests.contrib.flask.test_request.error",
          "trace_id": 0,
          "span_id": 6,
          "parent_id": 2,
          "error": 1,
          "meta": {
            "error.msg": "",
            "error.stack": "Traceback (most recent call last):\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/contrib/flask/wrappers.py\", line 25, in trace_func\n    return wrapped(*args, **kwargs)\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/tests/contrib/flask/test_request.py\", line 343, in error\n    raise Exception()\nException\n",
            "error.type": "builtins.Exception"
          },
          "duration": 1628000,
          "start": 1657055774809994000
        },
     {
       "name": "flask.handle_exception",
       "service": "flask",
       "resource": "flask.handle_exception",
       "trace_id": 0,
       "span_id": 3,
       "parent_id": 1,
       "duration": 1532000,
       "start": 1657055774814580000
     },
     {
       "name": "flask.do_teardown_request",
       "service": "flask",
       "resource": "flask.do_teardown_request",
       "trace_id": 0,
       "span_id": 4,
       "parent_id": 1,
       "duration": 36000,
       "start": 1657055774816403000
     },
     {
       "name": "flask.do_teardown_appcontext",
       "service": "flask",
       "resource": "flask.do_teardown_appcontext",
       "trace_id": 0,
       "span_id": 5,
       "parent_id": 1,
       "duration": 14000,
       "start": 1657055774816495000
     }]]
