[[
  {
    "name": "flask.request",
    "service": "flask",
    "resource": "GET /helloworld",
    "trace_id": 0,
    "span_id": 1,
    "parent_id": 0,
    "type": "web",
    "error": 1,
    "meta": {
      "_dd.p.dm": "-0",
      "flask.endpoint": "error",
      "flask.url_rule": "/helloworld",
      "flask.version": "1.1.4",
      "http.method": "GET",
      "http.status_code": "500",
      "http.url": "http://localhost/helloworld",
      "runtime-id": "bc0bb4c693774b23b717ab1b83bbe098"
    },
    "metrics": {
      "_dd.agent_psr": 1.0,
      "_dd.measured": 1,
      "_dd.top_level": 1,
      "_dd.tracer_kr": 1.0,
      "_sampling_priority_v1": 1,
      "system.pid": 48815
    },
    "duration": 5069000,
    "start": 1657055779910308000
  },
     {
       "name": "flask.try_trigger_before_first_request_functions",
       "service": "flask",
       "resource": "flask.try_trigger_before_first_request_functions",
       "trace_id": 0,
       "span_id": 2,
       "parent_id": 1,
       "error": 1,
       "meta": {
         "error.msg": "",
         "error.stack": "Traceback (most recent call last):\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/contrib/flask/helpers.py\", line 36, in wrapper\n    return wrapped(*args, **kwargs)\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/.riot/venv_py3615_flask~110_itsdangerous210_markupsafe20_werkzeug20/lib/python3.6/site-packages/flask/app.py\", line 1993, in try_trigger_before_first_request_functions\n    func()\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/contrib/flask/wrappers.py\", line 25, in trace_func\n    return wrapped(*args, **kwargs)\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/tests/contrib/flask/test_request.py\", line 343, in error\n    raise Exception()\nException\n",
         "error.type": "builtins.Exception"
       },
       "duration": 2976000,
       "start": 1657055779910858000
     },
        {
          "name": "tests.contrib.flask.test_request.error",
          "service": "flask",
          "resource": "tests.contrib.flask.test_request.error",
          "trace_id": 0,
          "span_id": 6,
          "parent_id": 2,
          "error": 1,
          "meta": {
            "error.msg": "",
            "error.stack": "Traceback (most recent call last):\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/ddtrace/contrib/flask/wrappers.py\", line 25, in trace_func\n    return wrapped(*args, **kwargs)\n  File \"/Users/munir.abdinur/Documents/ApmPython/dd-trace-py/tests/contrib/flask/test_request.py\", line 343, in error\n    raise Exception()\nException\n",
            "error.type": "builtins.Exception"
          },
          "duration": 428000,
          "start": 1657055779910901000
        },
     {
       "name": "flask.handle_exception",
       "service": "flask",
       "resource": "flask.handle_exception",
       "trace_id": 0,
       "span_id": 3,
       "parent_id": 1,
       "duration": 1021000,
       "start": 1657055779913933000
     },
        {
          "name": "flask.process_response",
          "service": "flask",
          "resource": "flask.process_response",
          "trace_id": 0,
          "span_id": 7,
          "parent_id": 3,
          "duration": 118000,
          "start": 1657055779914777000
        },
     {
       "name": "flask.do_teardown_request",
       "service": "flask",
       "resource": "flask.do_teardown_request",
       "trace_id": 0,
       "span_id": 4,
       "parent_id": 1,
       "duration": 42000,
       "start": 1657055779915233000
     },
     {
       "name": "flask.do_teardown_appcontext",
       "service": "flask",
       "resource": "flask.do_teardown_appcontext",
       "trace_id": 0,
       "span_id": 5,
       "parent_id": 1,
       "duration": 14000,
       "start": 1657055779915321000
     }]]
